config/routes.rb
Rails.application.routes.draw do

  root 'sessions#index'

  resources :qy_apps

  resources :orders

  match 'qy_wechat_auth_callback', to: 'sessions#callback', via: :get

end

app/models/qy_app.rb
class QyApp < ActiveRecord::Base

  before_create :init_qy_secret_key

  private

    def init_qy_secret_key
      self.qy_secret_key = SecureRandom.hex(8)
    end

end

app/controllers/qy_apps_controller.rb
class QyAppsController < ApplicationController
  before_filter :is_user_login
  before_action :set_qy_app, only: [:show, :edit, :update, :destroy]
# GET /qy_apps
# GET /qy_apps.json
  def index
    @qy_apps = QyApp.all
  end
# GET /qy_apps/1
# GET /qy_apps/1.json
  def show
  end
# GET /qy_apps/new
  def new
    @qy_app = QyApp.new
  end
# GET /qy_apps/1/edit
  def edit
  end
# POST /qy_apps
# POST /qy_apps.json
  def create
    @qy_app = QyApp.new(qy_app_params)
    respond_to do |format|
      if @qy_app.save
        format.html { redirect_to @qy_app, notice: 'Qy account was successfully created.' }
        format.json { render :show, status: :created, location: @qy_app }
      else
        format.html { render :new }
        format.json { render json: @qy_app.errors, status: :unprocessable_entity }
      end
    end
  end
# PATCH/PUT /qy_apps/1
# PATCH/PUT /qy_apps/1.json
  def update
    respond_to do |format|
      if @qy_app.update(qy_app_params)
        format.html { redirect_to @qy_app, notice: 'Qy account was successfully updated.' }
        format.json { render :show, status: :ok, location: @qy_app }
      else
        format.html { render :edit }
        format.json { render json: @qy_app.errors, status: :unprocessable_entity }
      end
    end
  end
# DELETE /qy_apps/1
# DELETE /qy_apps/1.json
  def destroy
    @qy_app.destroy
    respond_to do |format|
      format.html { redirect_to qy_apps_url, notice: 'Qy account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
# Use callbacks to share common setup or constraints between actions.
  def set_qy_app
    @qy_app = QyApp.find(params[:id])
  end
# Never trust parameters from the scary internet, only allow the white list through.
  def qy_app_params
    params.require(:qy_app).permit(:name, :qy_token, :encoding_aes_key, :corp_id)
  end

  def is_user_login
    redirect_to root_path if !warden.authenticated?
  end

end

app/views/qy_apps/_form.html.erb
<%= form_for @qy_app, :html => { :class => 'form-horizontal' } do |f| %>
    <% if @qy_app.errors.any? %>
        <div id="error_explanation" class="row">
          <h2><%= pluralize(@qy_app.errors.count, "error") %> prohibited this qy_app from being saved:</h2>
          <ul>
            <% @qy_app.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field form-group">
      <%= f.label :name, :class => "col-sm-2 control-label" %>
      <div class="col-sm-10">
       <%= f.text_field :name, :class => 'form-control' %>
      </div>
    </div>
    <div class="field form-group">
      <%= f.label :qy_token, :class => "col-sm-2 control-label" %>
      <div class="col-sm-10">
      <%= f.text_field :qy_token, :class => 'form-control' %>
      </div>
    </div>
    <div class="field form-group">
      <%= f.label :corp_id, :class => "col-sm-2 control-label" %>
      <div class="col-sm-10">
      <%= f.text_field :corp_id, :class => 'form-control' %>
      </div>
    </div>
    <div class="field form-group">
      <%= f.label :encoding_aes_key, :class => "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :encoding_aes_key, :class => 'form-control' %>
      </div>
    </div>
    <div class="actions form-group row">
      <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Submit', :class => 'form-control' %>
        </div>
    </div>
<% end %>

app/views/qy_apps/edit.html.erb
<h1>Editing qy_app</h1>
<%= render 'form' %>
<%= link_to 'Show', @qy_app %> |
<%= link_to 'Back', qy_apps_path %>

app/views/qy_apps/index.html.erb
<h1>Listing qy_apps</h1>
<div class="table-responsive">
<table class="table table-bordered table-hover">
  <thead>
  <tr>
    <th>Name</th>
    <th>URL</th>
    <th colspan="3">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @qy_apps.each do |qy_app| %>
      <tr>
        <td><%= qy_app.name %></td>
        <td><%= qy_wechat_engine.qy_verify_url(qy_app.qy_secret_key) %></td>
        <td><%= link_to 'Show', qy_app %></td>
        <td><%= link_to 'Edit', edit_qy_app_path(qy_app) %></td>
        <td><%= link_to 'Destroy', qy_app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>
</div>
<br>
<%= link_to 'New Qy app', new_qy_app_path %>

app/views/qy_apps/new.html.erb
<h1>New qy_app</h1>
<%= render 'form' %>
<%= link_to 'Back', qy_apps_path %>

app/views/qy_apps/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @qy_app.name %>
</p>
<%= link_to 'Edit', edit_qy_app_path(@qy_app) %> |
<%= link_to 'Back', qy_apps_path %>