config/routes.rb
Rails.application.routes.draw do

  root 'sessions#index'

  resources :qy_apps

  resources :orders

  match 'qy_wechat_auth_callback', to: 'sessions#callback', via: :get

end

app/models/order.rb
class Order < ActiveRecord::Base

  validates :product_name, presence: true
  validates :quantity, presence: true
  validates :unit_price, presence: true
  validates :total, presence: true

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_filter :load_order, only: [:show, :edit, :update, :destroy]

  def index
    @orders = Order.all
  end

  def show
  end

  def new
    @order = Order.new
  end

  def edit
  end

  def create
    @order = Order.new(order_params)
    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def load_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:product_name, :quantity, :unit_price, :total, :cost_unit_price)
    end

end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
    <% if @order.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>
          <ul>
            <% @order.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :product_name %><br>
      <%= f.text_field :product_name %>
    </div>
    <div class="field">
      <%= f.label :unit_price %><br>
      <%= f.text_field :unit_price %>
    </div>
    <div class="field">
      <%= f.label :quantity %><br>
      <%= f.text_field :quantity %>
    </div>
    <div class="field">
      <%= f.label :total %><br>
      <%= f.text_field :total %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>
<%= render 'form' %>
<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>unit price</th>
    <th>quantity</th>
    <th>total</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
      <tr>
        <td><%= order.product_name %></td>
        <td><%= order.unit_price %></td>
        <td><%= order.quantity %></td>
        <td><%= order.total %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>
<%= render 'form' %>
<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>product name:</strong>
  <%= @order.product_name %>
</p>
<p>
  <strong>unit price:</strong>
  <%= @order.unit_price %>
</p>
<p>
  <strong>total:</strong>
  <%= @order.total %>
</p>
<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>